---
title: "Muana Loa CO2 Data"
author: "Marc Los Huertos"
date: "2/3/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Importing Data into R

this is text
```{r}
maunaloa.csv <- "maunaloa.csv"
maunaloa.df <- read.csv(maunaloa.csv)
```



```{r, echo=TRUE, eval=TRUE}
str(maunaloa.df)
head(maunaloa.df)[,c(1,2,4)]
```


# Making a Plot

## Histogram...

```{r, echo=T}
hist(maunaloa.df$average)
mean(maunaloa.df$average)

library(zoo) # moving averages
par(mfrow=c(2,2))
plot(rollmean(maunaloa.df$average, 1), ty='l')
plot(rollmean(maunaloa.df$average, 2), ty='l')
plot(rollmean(maunaloa.df$average, 4), ty='l')
plot(rollmean(maunaloa.df$average, 12), ty='l')
par(mfrow=c(1,1))

```

co2 vs. year...

y = mx + b + error

y = f(x)



```{r, echo=FALSE}
attach(maunaloa.df)
plot(year, average)

plot(year, average, ty='l')





plot(decimal.date, average)

detach(maunaloa.df)







plot(maunaloa.df$decimal.date, maunaloa.df$average, ty='l', xlab = "Date", ylab = "CO2 Concentration (ppm)", main="Carbon Dioxide Concentration (Mauna Loa, HI)", las=1)

maunaloa.lm <- lm(average ~ decimal.date, data=maunaloa.df)
# str(maunaloa.lm)
coef(maunaloa.lm)

abline(coef(maunaloa.lm), col='red')
```


