\documentclass[12pt]{article}
\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{graphicx}
\setlength{\textheight}{10.1in}
\setlength{\topmargin}{-1.2in}
\setlength{\textwidth}{7in}
\setlength{\oddsidemargin}{-0.25in}
\newcommand{\zsp}{\rule{0pt}{5pt}}
\newcommand{\ind}{\zsp\hspace{6mm}}
\newcommand{\bzr}{{\bf 0}}
\newcommand{\ba}{{\bf a}}
\newcommand{\bb}{{\bf b}}
\newcommand{\bc}{{\bf c}}
\newcommand{\be}{{\bf e}}
\newcommand{\bs}{{\bf s}}
\newcommand{\bp}{{\bf p}}
\newcommand{\bx}{{\bf x}}
\newcommand{\by}{{\bf y}}
\newcommand{\bz}{{\bf z}}
\newcommand{\bu}{{\bf u}}
\newcommand{\bv}{{\bf v}}
\newcommand{\bw}{{\bf w}}
\newcommand{\yp}{\frac{dy}{dt}}
\newcommand{\ypp}{\frac{d^2y}{dt^2}}
\newcommand{\Dint}{\displaystyle\int}
\begin{document}
\LARGE
\thispagestyle{empty}

\subsection{Population Growth Models}

<<>>=
day = c(0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10) 
N = c(10, 14, 19, 24, 28, 38, 55, 72, 85, 123, 136)
q1.df = data.frame(Day = day, Population = N)
@

<<>>=
plot(Population ~ Day, data=q1.df)
@


b) For more data, use {\bf linear regression}: given\\\ind
$(t_0,P_0), (t_1,P_1),\ldots,(t_{N-1},P_{N-1})$; find $r, \ln(K)$ 
\\\ind to minimize 
$\sum_{n=0}^{N-1}(\ln(P_n)-\ln(K)-rt_n)^2$.\\\vspace{1in}


Computer solution: $r\approx .26463$, $K \approx 10.563$ 

%\begin{center}\includegraphics[width=1\textwidth]{fruitfly}\end{center}

\newpage\begin{center}{\bf POPULATION GROWTH MODELS CONT.}\end{center}

Logistic Growth Model: $P' = r(1-P/K)P$. \\
Modeling considers $b$ and $d$ to be dependent on size of $P$;\\
$K$ is {\bf carrying capacity} for population environment.   
\begin{itemize}
\item Qualitative analysis: \\
Equilibrium solutions?\\
Stable or Unstable?\vspace{.5in}

Logistic Equation Solution:\vspace{5.5in}

$$P(t) = K/\big(1+(K/P_0-1)e^{-r(t-t_0)}\big).$$
\end{itemize}
\newpage\begin{center}{\bf POPULATION GROWTH MODELS CONT.}\end{center}

Logistic Model Examples: 

\begin{itemize}
\item $P_0 = 1000$, $P(8)=1200$, eventual $P(t)$ is $20000$.\\\ind
Find $r$, and $t$ when $P(t)$ is 75\% of $K$.\vspace{3.75in}

%\begin{center}\includegraphics[width=.8\textwidth]{logit}\end{center}

\newpage
\item More Fruit Fly Data\vspace{-3mm}
\begin{verbatim}
Day  0   3   7   9  12  15  18  21  24  28  32 
Pop  6  10  21  52  67 104 163 226 265 282 319
\end{verbatim}
Estimate $r$, $K$; and check model.
$$P(t) = K/\big(1+(K/P_0-1)e^{-r(t-t_0)}\big).$$
For $r, K$, use 2 times, e.g. $t = 12, 24$, so\\\ind
\ $67 = K/(1+(K/6-1)e^{-12r})$, and\\\ind
$265 = K/(1+(K/6-1)e^{-24r})$.\\
Eliminate $K$ and solve for $a=e^{-12r}$;

\vspace{1in}

\ind
$K = 67(1-a)/(1-67a/6)$,\\\ind $K = 265(1-a^2)/(1-265a^2/6)$,\\\ind 
$(1-265a^2/6) = 265(1+a)(1-67a/6)/67$;\\\ind
$265/67-1 = 265(61)a/(67\cdot 6);$ $a \approx .0735$, \\$r\approx .218$, 
$K\approx 260?$, not consistent with data.\\

Try other data to find $K,\ r$? \\\ind 
Need to solve nonlinear equation for $r$.\\\ind
Could use nonlinear least-squares fit.
\end{itemize}

US Population Modeling?\\
Can try to fit a logistic model, but predictions not good.\\
Need a model that includes immigration: e.g.
$$P' = r(1-P/K)P + I$$ 
for immigration rate I, or
$$P' = r(t)(1-P/K)P + I(t).$$ 

\end{document}