---
title: "cote"
author: "Clare Flynn"
date: "September 2, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}

eer.csv <- "../Clareflynn/EERLGR.csv"
EER <- read.csv(eer.csv)

ji.csv = "../Clareflynn/JILGRnew.csv"
JI <- read.csv(ji.csv)

mr.csv <- "../Clareflynn/MRLGRnew.csv"
MR <- read.csv(mr.csv)

ogi.csv <- "../Clareflynn/OGI.csv"
OGI <- read.csv(ogi.csv)

pi.csv <- "../Clareflynn/PINWR.csv"
PINWR <- read.csv(pi.csv)

sinwr.csv <- "../Clareflynn/SINWR.csv"
SINWR <- read.csv(sinwr.csv)

sti.csv <- "../Clareflynn/STI.csv"
STI <- read.csv(sti.csv)




names(JI)
names(EER)
names(MR)
names(OGI)
names(PINWR)
names(SINWR)
names(STI)

joined = rbind(JI, EER, MR, OGI, PINWR, SINWR, STI)

boxplot(LGR ~ Hatch_Order, data=joined)

summary(aov(LGR ~ Hatch_Order, data=joined))

boxplot(joined$LGR~joined$Island.Alpha)
```


## Combining Hatch Order Categories

```{r}	
levels(joined$Hatch_Order) <- list(A=c("A" , "A1"), O=c("B", "C"))

boxplot(LGR ~ Hatch_Order, data=joined)

summary(aov(LGR ~ Hatch_Order, data=joined))

joined$Region <- "Inner"
joined$Region[joined$Island.Alpha=="SINWR"] <- "Outer"
joined$Region[joined$Island.Alpha=="MR"] <- "Outer"
#joined$Region[joined$Island.Alpha=="EER"] <- "Outer"

boxplot(LGR ~ Region, data=joined)

summary(aov(LGR ~ Region, data=joined[joined$Hatch_Order=='A',]))
summary(aov(LGR ~ Region, data=joined[joined$Hatch_Order=='O',]))
boxplot(LGR ~ Region, data=joined[joined$Hatch_Order=='A',])
boxplot(LGR ~ Region, data=joined[joined$Hatch_Order=='O',])

summary(test <- aov(LGR ~ Island.Alpha, data=joined))
TukeyHSD(test, "Island.Alpha", ordered = FALSE)
plot(TukeyHSD(test, "Alpha.Island"))

summary(test <- aov(LGR ~ Region + Hatch_Order, data=joined))
TukeyHSD(test, "Region", ordered = FALSE)
plot(TukeyHSD(test, "Region"))

summary(test <- aov(LGR ~ Island.Alpha + Region, data=joined))
TukeyHSD(test, "Island.Alpha", ordered = FALSE)
plot(TukeyHSD(test, "Alpha.Island"))

#inner <- rbind(PINWR, OGI, JI, STI)
#outer <- rbind(SINWR, MR, EER)

#levels(inner$Hatch_Order) <- list(A=c("A" , "A1"), O=c("B", "C"))
#levels(outer$Hatch_Order) <- list(A=c("A" , "A1"), O=c("B", "C"))

#EER <- read.csv("/Users/clareflynn/Desktop/EERLGR.csv")
#JI <- read.csv("/Users/clareflynn/Desktop/JILGRnew.csv")
#MR <- read.csv("/Users/clareflynn/Desktop/MRLGRnew.csv")
#OGI <- read.csv("/Users/clareflynn/Desktop/OGILGRnew.csv")
#PI <- read.csv("/Users/clareflynn/Desktop/PINWR.csv")
#SINWR <- read.csv("/Users/clareflynn/Desktop/SINWR.csv")
#STI <- read.csv("/Users/clareflynn/Desktop/STI.csv")


#EERA <- EER$LGR[which(EER$Hatch_Order=='A')]
#EERB <- EER$LGR[which(EER$Hatch_Order=='B')]
#JIA <- JI$LGR[which(JI$Hatch_Order=='A')]
#JIB <- JI$LGR[which(JI$Hatch_Order=='B')]
#MRA <- MR$LGR[which(MR$Hatch_Order=='A')]
#MRB <- MR$LGR[which(MR$Hatch_Order=='B')]
#OGIA <- OGI$LGR[which(OGI$Hatch_Order=='A')]
#OGIB <- OGI$LGR[which(OGI$Hatch_Order=='B')]
#PIA <- PI$LGR[which(PI$Hatch_Order=='A')]
#PIB <- PI$LGR[which(PI$Hatch_Order=='B')]
#SINWRA <- SINWR$LGR[which(SINWR$Hatch_Order=='A')]
#SINWRB <- SINWR$LGR[which(SINWR$Hatch_Order=='B')]
#STIA <- STI$LGR[which(STI$Hatch_Order=='A')]
#STIB <- STI$LGR[which(STI$Hatch_Order=='B')]

#comb <- cbind(EERA, JIA, MRA, OGIA, PIA, SINWRA, STIA, EERB, JIB, MRB, OGIB, PIB, SINWRB, STIB)
#PIcomb <- cbind(PIA, PIB)
#SINWRcomb <- cbind(SINWRA, SINWRB)
```
