---
title: "beginnersluck Respository"
author: "Marc Los Huertos"
date: "`r Sys.Date()`"
output:
  html_document:
    theme: "flatly"
    highlight: textmate
    toc: false
    self_contained: true
    css: marclos2.css
---

## Respository to test half-baked ideas and resources 

I am use my [beginnersluck](https://github.com/marclos/Beginnersluck) repository to host various R and RStudio related "draft" projects including teaching materials, Shiny apps, and other R related resources. These are often formalized into their own repositories later on, but this "sandbox" is used to test and share ideas in the meantime.

You can also access all my repositories via [marclos](https://github.com/marclos).

### EA010 Resources

#### Environmental Economics

#### R Shiny Apps
 - [Supply and Demand](environmental_econ/supply_and_demand_v_0.2.R)
 - [Cap and Trade](environmental_econ/Cap_and_Trade_v_1.0.R)
 
#### Teaching Materials
 - [Social_Cost_of_Carbon-Discounting](environmental_econ/Social_Cost_of_Carbon_Discounting/Discounting.html)
 
### EA030 Resources

#### Statistic Resources

 - [R Reference Card](R/R_Reference_Card.pdf)
 
#### R Scripts



### EA Course Plans

 - [EA Course Plan Fall 2025](Course_Plans_F2025.pdf)
 - [EA Course Plan Spring 2026 -- NOT DONE YET]