---
title: "Beginnersluck"
author: "Your Name"
output:
  html_document:
    theme: "flatly"
    highlight: textmate
    toc: false
    self_contained: true
    css: styles.css
---

# Beginnersluck  
## A repository for new users to play via RStudio  

Welcome to a **Beginners Guide to R, RStudio, and GitHub**.

Here’s a [link to a description of doing statistics in R](#).

### Designer Templates  
We’ve crafted some handsome templates for you to use. Go ahead and click “Continue to layouts” to browse through them. You can easily go back to edit your page before publishing. After publishing your page, you can revisit the page generator and switch to another theme. Your Page content will be preserved.

### Creating pages manually  
If you prefer to not use the automatic generator, push a branch named `gh-pages` to your repository to create a page manually. In addition to supporting regular HTML content, GitHub Pages supports Jekyll, a simple, blog-aware static site generator. Jekyll makes it easy to create site-wide headers and footers without having to copy them across every page. It also offers intelligent blog support and other advanced templating features.

### Authors and Contributors  
You can @mention a GitHub username to generate a link to their profile. For example: In 2007, Chris Wanstrath (@defunkt), PJ Hyett (@pjhyett), and Tom Preston-Werner (@mojombo) founded GitHub.

### Support or Contact  
Having trouble with Pages? Check out the [documentation](https://help.github.com/pages) or [contact support](https://github.com/contact) and we’ll help you sort it out.

[Beginnersluck repository](https://github.com/your-username/your-repo) is maintained by [your-username](https://github.com/your-username).
